version: 2
jobs:
  node10:
    docker:
      - image: node:10-alpine
    steps: &buildSteps
      - run: apk add --no-cache git
      - checkout
      - run: yarn
      - run: yarn test
  node12:
    docker:
      - image: node:12-alpine
    steps: *buildSteps
  node14:
    docker:
      - image: node:14-alpine
    steps: *buildSteps
  node15:
    docker:
      - image: node:15-alpine
    steps: *buildSteps
workflows:
  version: 2
  test:
    jobs:
      - node10
      - node12
      - node14
      - node15
