version: 2
jobs:
  node8:
    docker:
      - image: node:8-alpine
    steps: &buildSteps
      - run: apk add --no-cache git
      - checkout
      - run: yarn
      - run: yarn test
  node10:
    docker:
      - image: node:10-alpine
    steps: *buildSteps
  node11:
    docker:
      - image: node:11-alpine
    steps: *buildSteps
  node12:
    docker:
      - image: node:12-alpine
    steps: *buildSteps
workflows:
  version: 2
  test:
    jobs:
      - node8
      - node10
      - node11
      - node12
